import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers";
import { headers } from "next/headers";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const EXCLUDED_PATHS = ["/closed"];

async function getTenant() {
  const headersList = await headers();
  const domain = headersList.get("host")?.split(":")[0];
  
  if (!domain) return null;
  
  return await prisma.tenant.findUnique({
    where: { domain },
    select: { id: true, name: true, title: true, logo: true, favicon: true }
  });
  
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tenant = await getTenant();
  metadata.title = tenant?.name || "App";
  metadata.description = tenant?.title || "App";
  if (!tenant) {
    return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
          <div className="min-h-screen flex items-center justify-center bg-gray-50">
            <div className="text-center p-8">
              <h1 className="text-4xl font-bold text-gray-900 mb-4">Bayi Erişimi Kapalı</h1>
              <p className="text-gray-600">Bu bayi şu anda hizmet verememektedir.</p>
            </div>
          </div>
        </body>
      </html>
    );
  }
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {tenant.favicon && <link rel="icon" href={tenant.favicon} />}
          <title>{tenant.title || "App"}</title>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
